// <auto-generated />
using Academy2.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Academy2.Migrations
{
    [DbContext(typeof(Academy2Context))]
    [Migration("20260416081448_mssql.local_migration_236")]
    partial class mssqllocal_migration_236
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Academy2.Models.Direction", b =>
                {
                    b.Property<byte>("direction_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<byte>("direction_id"));

                    b.Property<string>("direction_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("direction_id");

                    b.ToTable("Direction");
                });
#pragma warning restore 612, 618
        }
    }
}
